//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webServiceClient2.BorlandWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        private int AgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BorlandWS.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name A_ReadMeFirstResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/A_ReadMeFirst", ReplyAction="*")]
        webServiceClient2.BorlandWS.A_ReadMeFirstResponse A_ReadMeFirst(webServiceClient2.BorlandWS.A_ReadMeFirstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/A_ReadMeFirst", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.A_ReadMeFirstResponse> A_ReadMeFirstAsync(webServiceClient2.BorlandWS.A_ReadMeFirstRequest request);
        
        // CODEGEN: Generating message contract since element name sString from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/echoString", ReplyAction="*")]
        webServiceClient2.BorlandWS.echoStringResponse echoString(webServiceClient2.BorlandWS.echoStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/echoString", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.echoStringResponse> echoStringAsync(webServiceClient2.BorlandWS.echoStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/echoFloat", ReplyAction="*")]
        float echoFloat(float fFloat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/echoFloat", ReplyAction="*")]
        System.Threading.Tasks.Task<float> echoFloatAsync(float fFloat);
        
        // CODEGEN: Generating message contract since element name aStringArray from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/echoStringArray", ReplyAction="*")]
        webServiceClient2.BorlandWS.echoStringArrayResponse echoStringArray(webServiceClient2.BorlandWS.echoStringArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/echoStringArray", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.echoStringArrayResponse> echoStringArrayAsync(webServiceClient2.BorlandWS.echoStringArrayRequest request);
        
        // CODEGEN: Generating message contract since element name aObjectArray from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/echoObjectArray", ReplyAction="*")]
        webServiceClient2.BorlandWS.echoObjectArrayResponse echoObjectArray(webServiceClient2.BorlandWS.echoObjectArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/echoObjectArray", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.echoObjectArrayResponse> echoObjectArrayAsync(webServiceClient2.BorlandWS.echoObjectArrayRequest request);
        
        // CODEGEN: Generating message contract since element name GetNowAsShortStringResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNowAsShortString", ReplyAction="*")]
        webServiceClient2.BorlandWS.GetNowAsShortStringResponse GetNowAsShortString(webServiceClient2.BorlandWS.GetNowAsShortStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNowAsShortString", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.GetNowAsShortStringResponse> GetNowAsShortStringAsync(webServiceClient2.BorlandWS.GetNowAsShortStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNowAsDate", ReplyAction="*")]
        System.DateTime GetNowAsDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNowAsDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetNowAsDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandomNumber", ReplyAction="*")]
        int GetRandomNumber(int nMin, int nMax);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRandomNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetRandomNumberAsync(int nMin, int nMax);
        
        // CODEGEN: Generating message contract since element name sFirstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserInformation", ReplyAction="*")]
        webServiceClient2.BorlandWS.SetUserInformationResponse SetUserInformation(webServiceClient2.BorlandWS.SetUserInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.SetUserInformationResponse> SetUserInformationAsync(webServiceClient2.BorlandWS.SetUserInformationRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserInformationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInformation", ReplyAction="*")]
        webServiceClient2.BorlandWS.GetUserInformationResponse GetUserInformation(webServiceClient2.BorlandWS.GetUserInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.GetUserInformationResponse> GetUserInformationAsync(webServiceClient2.BorlandWS.GetUserInformationRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserObjectResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserObject", ReplyAction="*")]
        webServiceClient2.BorlandWS.GetUserObjectResponse GetUserObject(webServiceClient2.BorlandWS.GetUserObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserObject", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.GetUserObjectResponse> GetUserObjectAsync(webServiceClient2.BorlandWS.GetUserObjectRequest request);
        
        // CODEGEN: Generating message contract since element name usr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserObject", ReplyAction="*")]
        webServiceClient2.BorlandWS.SetUserObjectResponse SetUserObject(webServiceClient2.BorlandWS.SetUserObjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetUserObject", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.SetUserObjectResponse> SetUserObjectAsync(webServiceClient2.BorlandWS.SetUserObjectRequest request);
        
        // CODEGEN: Generating message contract since element name usr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IncreaseUserAge", ReplyAction="*")]
        webServiceClient2.BorlandWS.IncreaseUserAgeResponse IncreaseUserAge(webServiceClient2.BorlandWS.IncreaseUserAgeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IncreaseUserAge", ReplyAction="*")]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.IncreaseUserAgeResponse> IncreaseUserAgeAsync(webServiceClient2.BorlandWS.IncreaseUserAgeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class A_ReadMeFirstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="A_ReadMeFirst", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.A_ReadMeFirstRequestBody Body;
        
        public A_ReadMeFirstRequest() {
        }
        
        public A_ReadMeFirstRequest(webServiceClient2.BorlandWS.A_ReadMeFirstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class A_ReadMeFirstRequestBody {
        
        public A_ReadMeFirstRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class A_ReadMeFirstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="A_ReadMeFirstResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.A_ReadMeFirstResponseBody Body;
        
        public A_ReadMeFirstResponse() {
        }
        
        public A_ReadMeFirstResponse(webServiceClient2.BorlandWS.A_ReadMeFirstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class A_ReadMeFirstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webServiceClient2.BorlandWS.ArrayOfString A_ReadMeFirstResult;
        
        public A_ReadMeFirstResponseBody() {
        }
        
        public A_ReadMeFirstResponseBody(webServiceClient2.BorlandWS.ArrayOfString A_ReadMeFirstResult) {
            this.A_ReadMeFirstResult = A_ReadMeFirstResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="echoString", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.echoStringRequestBody Body;
        
        public echoStringRequest() {
        }
        
        public echoStringRequest(webServiceClient2.BorlandWS.echoStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class echoStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sString;
        
        public echoStringRequestBody() {
        }
        
        public echoStringRequestBody(string sString) {
            this.sString = sString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="echoStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.echoStringResponseBody Body;
        
        public echoStringResponse() {
        }
        
        public echoStringResponse(webServiceClient2.BorlandWS.echoStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class echoStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string echoStringResult;
        
        public echoStringResponseBody() {
        }
        
        public echoStringResponseBody(string echoStringResult) {
            this.echoStringResult = echoStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoStringArrayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="echoStringArray", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.echoStringArrayRequestBody Body;
        
        public echoStringArrayRequest() {
        }
        
        public echoStringArrayRequest(webServiceClient2.BorlandWS.echoStringArrayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class echoStringArrayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webServiceClient2.BorlandWS.ArrayOfString aStringArray;
        
        public echoStringArrayRequestBody() {
        }
        
        public echoStringArrayRequestBody(webServiceClient2.BorlandWS.ArrayOfString aStringArray) {
            this.aStringArray = aStringArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoStringArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="echoStringArrayResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.echoStringArrayResponseBody Body;
        
        public echoStringArrayResponse() {
        }
        
        public echoStringArrayResponse(webServiceClient2.BorlandWS.echoStringArrayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class echoStringArrayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webServiceClient2.BorlandWS.ArrayOfString echoStringArrayResult;
        
        public echoStringArrayResponseBody() {
        }
        
        public echoStringArrayResponseBody(webServiceClient2.BorlandWS.ArrayOfString echoStringArrayResult) {
            this.echoStringArrayResult = echoStringArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoObjectArrayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="echoObjectArray", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.echoObjectArrayRequestBody Body;
        
        public echoObjectArrayRequest() {
        }
        
        public echoObjectArrayRequest(webServiceClient2.BorlandWS.echoObjectArrayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class echoObjectArrayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webServiceClient2.BorlandWS.User[] aObjectArray;
        
        public echoObjectArrayRequestBody() {
        }
        
        public echoObjectArrayRequestBody(webServiceClient2.BorlandWS.User[] aObjectArray) {
            this.aObjectArray = aObjectArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoObjectArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="echoObjectArrayResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.echoObjectArrayResponseBody Body;
        
        public echoObjectArrayResponse() {
        }
        
        public echoObjectArrayResponse(webServiceClient2.BorlandWS.echoObjectArrayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class echoObjectArrayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webServiceClient2.BorlandWS.User[] echoObjectArrayResult;
        
        public echoObjectArrayResponseBody() {
        }
        
        public echoObjectArrayResponseBody(webServiceClient2.BorlandWS.User[] echoObjectArrayResult) {
            this.echoObjectArrayResult = echoObjectArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNowAsShortStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNowAsShortString", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.GetNowAsShortStringRequestBody Body;
        
        public GetNowAsShortStringRequest() {
        }
        
        public GetNowAsShortStringRequest(webServiceClient2.BorlandWS.GetNowAsShortStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNowAsShortStringRequestBody {
        
        public GetNowAsShortStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNowAsShortStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNowAsShortStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.GetNowAsShortStringResponseBody Body;
        
        public GetNowAsShortStringResponse() {
        }
        
        public GetNowAsShortStringResponse(webServiceClient2.BorlandWS.GetNowAsShortStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNowAsShortStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNowAsShortStringResult;
        
        public GetNowAsShortStringResponseBody() {
        }
        
        public GetNowAsShortStringResponseBody(string GetNowAsShortStringResult) {
            this.GetNowAsShortStringResult = GetNowAsShortStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserInformation", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.SetUserInformationRequestBody Body;
        
        public SetUserInformationRequest() {
        }
        
        public SetUserInformationRequest(webServiceClient2.BorlandWS.SetUserInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sFirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sLastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int nAge;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sStreet;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sCity;
        
        public SetUserInformationRequestBody() {
        }
        
        public SetUserInformationRequestBody(string sFirstName, string sLastName, int nAge, string sStreet, string sCity) {
            this.sFirstName = sFirstName;
            this.sLastName = sLastName;
            this.nAge = nAge;
            this.sStreet = sStreet;
            this.sCity = sCity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserInformationResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.SetUserInformationResponseBody Body;
        
        public SetUserInformationResponse() {
        }
        
        public SetUserInformationResponse(webServiceClient2.BorlandWS.SetUserInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetUserInformationResult;
        
        public SetUserInformationResponseBody() {
        }
        
        public SetUserInformationResponseBody(bool SetUserInformationResult) {
            this.SetUserInformationResult = SetUserInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformation", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.GetUserInformationRequestBody Body;
        
        public GetUserInformationRequest() {
        }
        
        public GetUserInformationRequest(webServiceClient2.BorlandWS.GetUserInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUserInformationRequestBody {
        
        public GetUserInformationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserInformationResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.GetUserInformationResponseBody Body;
        
        public GetUserInformationResponse() {
        }
        
        public GetUserInformationResponse(webServiceClient2.BorlandWS.GetUserInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserInformationResult;
        
        public GetUserInformationResponseBody() {
        }
        
        public GetUserInformationResponseBody(string GetUserInformationResult) {
            this.GetUserInformationResult = GetUserInformationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserObject", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.GetUserObjectRequestBody Body;
        
        public GetUserObjectRequest() {
        }
        
        public GetUserObjectRequest(webServiceClient2.BorlandWS.GetUserObjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUserObjectRequestBody {
        
        public GetUserObjectRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserObjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.GetUserObjectResponseBody Body;
        
        public GetUserObjectResponse() {
        }
        
        public GetUserObjectResponse(webServiceClient2.BorlandWS.GetUserObjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserObjectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webServiceClient2.BorlandWS.User GetUserObjectResult;
        
        public GetUserObjectResponseBody() {
        }
        
        public GetUserObjectResponseBody(webServiceClient2.BorlandWS.User GetUserObjectResult) {
            this.GetUserObjectResult = GetUserObjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserObjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserObject", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.SetUserObjectRequestBody Body;
        
        public SetUserObjectRequest() {
        }
        
        public SetUserObjectRequest(webServiceClient2.BorlandWS.SetUserObjectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserObjectRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webServiceClient2.BorlandWS.User usr;
        
        public SetUserObjectRequestBody() {
        }
        
        public SetUserObjectRequestBody(webServiceClient2.BorlandWS.User usr) {
            this.usr = usr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserObjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserObjectResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.SetUserObjectResponseBody Body;
        
        public SetUserObjectResponse() {
        }
        
        public SetUserObjectResponse(webServiceClient2.BorlandWS.SetUserObjectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserObjectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetUserObjectResult;
        
        public SetUserObjectResponseBody() {
        }
        
        public SetUserObjectResponseBody(bool SetUserObjectResult) {
            this.SetUserObjectResult = SetUserObjectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseUserAgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IncreaseUserAge", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.IncreaseUserAgeRequestBody Body;
        
        public IncreaseUserAgeRequest() {
        }
        
        public IncreaseUserAgeRequest(webServiceClient2.BorlandWS.IncreaseUserAgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IncreaseUserAgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webServiceClient2.BorlandWS.User usr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int nIncrease;
        
        public IncreaseUserAgeRequestBody() {
        }
        
        public IncreaseUserAgeRequestBody(webServiceClient2.BorlandWS.User usr, int nIncrease) {
            this.usr = usr;
            this.nIncrease = nIncrease;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncreaseUserAgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IncreaseUserAgeResponse", Namespace="http://tempuri.org/", Order=0)]
        public webServiceClient2.BorlandWS.IncreaseUserAgeResponseBody Body;
        
        public IncreaseUserAgeResponse() {
        }
        
        public IncreaseUserAgeResponse(webServiceClient2.BorlandWS.IncreaseUserAgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IncreaseUserAgeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public webServiceClient2.BorlandWS.User IncreaseUserAgeResult;
        
        public IncreaseUserAgeResponseBody() {
        }
        
        public IncreaseUserAgeResponseBody(webServiceClient2.BorlandWS.User IncreaseUserAgeResult) {
            this.IncreaseUserAgeResult = IncreaseUserAgeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : webServiceClient2.BorlandWS.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<webServiceClient2.BorlandWS.Service1Soap>, webServiceClient2.BorlandWS.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.A_ReadMeFirstResponse webServiceClient2.BorlandWS.Service1Soap.A_ReadMeFirst(webServiceClient2.BorlandWS.A_ReadMeFirstRequest request) {
            return base.Channel.A_ReadMeFirst(request);
        }
        
        public webServiceClient2.BorlandWS.ArrayOfString A_ReadMeFirst() {
            webServiceClient2.BorlandWS.A_ReadMeFirstRequest inValue = new webServiceClient2.BorlandWS.A_ReadMeFirstRequest();
            inValue.Body = new webServiceClient2.BorlandWS.A_ReadMeFirstRequestBody();
            webServiceClient2.BorlandWS.A_ReadMeFirstResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).A_ReadMeFirst(inValue);
            return retVal.Body.A_ReadMeFirstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.A_ReadMeFirstResponse> webServiceClient2.BorlandWS.Service1Soap.A_ReadMeFirstAsync(webServiceClient2.BorlandWS.A_ReadMeFirstRequest request) {
            return base.Channel.A_ReadMeFirstAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.A_ReadMeFirstResponse> A_ReadMeFirstAsync() {
            webServiceClient2.BorlandWS.A_ReadMeFirstRequest inValue = new webServiceClient2.BorlandWS.A_ReadMeFirstRequest();
            inValue.Body = new webServiceClient2.BorlandWS.A_ReadMeFirstRequestBody();
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).A_ReadMeFirstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.echoStringResponse webServiceClient2.BorlandWS.Service1Soap.echoString(webServiceClient2.BorlandWS.echoStringRequest request) {
            return base.Channel.echoString(request);
        }
        
        public string echoString(string sString) {
            webServiceClient2.BorlandWS.echoStringRequest inValue = new webServiceClient2.BorlandWS.echoStringRequest();
            inValue.Body = new webServiceClient2.BorlandWS.echoStringRequestBody();
            inValue.Body.sString = sString;
            webServiceClient2.BorlandWS.echoStringResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).echoString(inValue);
            return retVal.Body.echoStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.echoStringResponse> webServiceClient2.BorlandWS.Service1Soap.echoStringAsync(webServiceClient2.BorlandWS.echoStringRequest request) {
            return base.Channel.echoStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.echoStringResponse> echoStringAsync(string sString) {
            webServiceClient2.BorlandWS.echoStringRequest inValue = new webServiceClient2.BorlandWS.echoStringRequest();
            inValue.Body = new webServiceClient2.BorlandWS.echoStringRequestBody();
            inValue.Body.sString = sString;
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).echoStringAsync(inValue);
        }
        
        public float echoFloat(float fFloat) {
            return base.Channel.echoFloat(fFloat);
        }
        
        public System.Threading.Tasks.Task<float> echoFloatAsync(float fFloat) {
            return base.Channel.echoFloatAsync(fFloat);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.echoStringArrayResponse webServiceClient2.BorlandWS.Service1Soap.echoStringArray(webServiceClient2.BorlandWS.echoStringArrayRequest request) {
            return base.Channel.echoStringArray(request);
        }
        
        public webServiceClient2.BorlandWS.ArrayOfString echoStringArray(webServiceClient2.BorlandWS.ArrayOfString aStringArray) {
            webServiceClient2.BorlandWS.echoStringArrayRequest inValue = new webServiceClient2.BorlandWS.echoStringArrayRequest();
            inValue.Body = new webServiceClient2.BorlandWS.echoStringArrayRequestBody();
            inValue.Body.aStringArray = aStringArray;
            webServiceClient2.BorlandWS.echoStringArrayResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).echoStringArray(inValue);
            return retVal.Body.echoStringArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.echoStringArrayResponse> webServiceClient2.BorlandWS.Service1Soap.echoStringArrayAsync(webServiceClient2.BorlandWS.echoStringArrayRequest request) {
            return base.Channel.echoStringArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.echoStringArrayResponse> echoStringArrayAsync(webServiceClient2.BorlandWS.ArrayOfString aStringArray) {
            webServiceClient2.BorlandWS.echoStringArrayRequest inValue = new webServiceClient2.BorlandWS.echoStringArrayRequest();
            inValue.Body = new webServiceClient2.BorlandWS.echoStringArrayRequestBody();
            inValue.Body.aStringArray = aStringArray;
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).echoStringArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.echoObjectArrayResponse webServiceClient2.BorlandWS.Service1Soap.echoObjectArray(webServiceClient2.BorlandWS.echoObjectArrayRequest request) {
            return base.Channel.echoObjectArray(request);
        }
        
        public webServiceClient2.BorlandWS.User[] echoObjectArray(webServiceClient2.BorlandWS.User[] aObjectArray) {
            webServiceClient2.BorlandWS.echoObjectArrayRequest inValue = new webServiceClient2.BorlandWS.echoObjectArrayRequest();
            inValue.Body = new webServiceClient2.BorlandWS.echoObjectArrayRequestBody();
            inValue.Body.aObjectArray = aObjectArray;
            webServiceClient2.BorlandWS.echoObjectArrayResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).echoObjectArray(inValue);
            return retVal.Body.echoObjectArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.echoObjectArrayResponse> webServiceClient2.BorlandWS.Service1Soap.echoObjectArrayAsync(webServiceClient2.BorlandWS.echoObjectArrayRequest request) {
            return base.Channel.echoObjectArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.echoObjectArrayResponse> echoObjectArrayAsync(webServiceClient2.BorlandWS.User[] aObjectArray) {
            webServiceClient2.BorlandWS.echoObjectArrayRequest inValue = new webServiceClient2.BorlandWS.echoObjectArrayRequest();
            inValue.Body = new webServiceClient2.BorlandWS.echoObjectArrayRequestBody();
            inValue.Body.aObjectArray = aObjectArray;
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).echoObjectArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.GetNowAsShortStringResponse webServiceClient2.BorlandWS.Service1Soap.GetNowAsShortString(webServiceClient2.BorlandWS.GetNowAsShortStringRequest request) {
            return base.Channel.GetNowAsShortString(request);
        }
        
        public string GetNowAsShortString() {
            webServiceClient2.BorlandWS.GetNowAsShortStringRequest inValue = new webServiceClient2.BorlandWS.GetNowAsShortStringRequest();
            inValue.Body = new webServiceClient2.BorlandWS.GetNowAsShortStringRequestBody();
            webServiceClient2.BorlandWS.GetNowAsShortStringResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).GetNowAsShortString(inValue);
            return retVal.Body.GetNowAsShortStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.GetNowAsShortStringResponse> webServiceClient2.BorlandWS.Service1Soap.GetNowAsShortStringAsync(webServiceClient2.BorlandWS.GetNowAsShortStringRequest request) {
            return base.Channel.GetNowAsShortStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.GetNowAsShortStringResponse> GetNowAsShortStringAsync() {
            webServiceClient2.BorlandWS.GetNowAsShortStringRequest inValue = new webServiceClient2.BorlandWS.GetNowAsShortStringRequest();
            inValue.Body = new webServiceClient2.BorlandWS.GetNowAsShortStringRequestBody();
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).GetNowAsShortStringAsync(inValue);
        }
        
        public System.DateTime GetNowAsDate() {
            return base.Channel.GetNowAsDate();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetNowAsDateAsync() {
            return base.Channel.GetNowAsDateAsync();
        }
        
        public int GetRandomNumber(int nMin, int nMax) {
            return base.Channel.GetRandomNumber(nMin, nMax);
        }
        
        public System.Threading.Tasks.Task<int> GetRandomNumberAsync(int nMin, int nMax) {
            return base.Channel.GetRandomNumberAsync(nMin, nMax);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.SetUserInformationResponse webServiceClient2.BorlandWS.Service1Soap.SetUserInformation(webServiceClient2.BorlandWS.SetUserInformationRequest request) {
            return base.Channel.SetUserInformation(request);
        }
        
        public bool SetUserInformation(string sFirstName, string sLastName, int nAge, string sStreet, string sCity) {
            webServiceClient2.BorlandWS.SetUserInformationRequest inValue = new webServiceClient2.BorlandWS.SetUserInformationRequest();
            inValue.Body = new webServiceClient2.BorlandWS.SetUserInformationRequestBody();
            inValue.Body.sFirstName = sFirstName;
            inValue.Body.sLastName = sLastName;
            inValue.Body.nAge = nAge;
            inValue.Body.sStreet = sStreet;
            inValue.Body.sCity = sCity;
            webServiceClient2.BorlandWS.SetUserInformationResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).SetUserInformation(inValue);
            return retVal.Body.SetUserInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.SetUserInformationResponse> webServiceClient2.BorlandWS.Service1Soap.SetUserInformationAsync(webServiceClient2.BorlandWS.SetUserInformationRequest request) {
            return base.Channel.SetUserInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.SetUserInformationResponse> SetUserInformationAsync(string sFirstName, string sLastName, int nAge, string sStreet, string sCity) {
            webServiceClient2.BorlandWS.SetUserInformationRequest inValue = new webServiceClient2.BorlandWS.SetUserInformationRequest();
            inValue.Body = new webServiceClient2.BorlandWS.SetUserInformationRequestBody();
            inValue.Body.sFirstName = sFirstName;
            inValue.Body.sLastName = sLastName;
            inValue.Body.nAge = nAge;
            inValue.Body.sStreet = sStreet;
            inValue.Body.sCity = sCity;
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).SetUserInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.GetUserInformationResponse webServiceClient2.BorlandWS.Service1Soap.GetUserInformation(webServiceClient2.BorlandWS.GetUserInformationRequest request) {
            return base.Channel.GetUserInformation(request);
        }
        
        public string GetUserInformation() {
            webServiceClient2.BorlandWS.GetUserInformationRequest inValue = new webServiceClient2.BorlandWS.GetUserInformationRequest();
            inValue.Body = new webServiceClient2.BorlandWS.GetUserInformationRequestBody();
            webServiceClient2.BorlandWS.GetUserInformationResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).GetUserInformation(inValue);
            return retVal.Body.GetUserInformationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.GetUserInformationResponse> webServiceClient2.BorlandWS.Service1Soap.GetUserInformationAsync(webServiceClient2.BorlandWS.GetUserInformationRequest request) {
            return base.Channel.GetUserInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.GetUserInformationResponse> GetUserInformationAsync() {
            webServiceClient2.BorlandWS.GetUserInformationRequest inValue = new webServiceClient2.BorlandWS.GetUserInformationRequest();
            inValue.Body = new webServiceClient2.BorlandWS.GetUserInformationRequestBody();
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).GetUserInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.GetUserObjectResponse webServiceClient2.BorlandWS.Service1Soap.GetUserObject(webServiceClient2.BorlandWS.GetUserObjectRequest request) {
            return base.Channel.GetUserObject(request);
        }
        
        public webServiceClient2.BorlandWS.User GetUserObject() {
            webServiceClient2.BorlandWS.GetUserObjectRequest inValue = new webServiceClient2.BorlandWS.GetUserObjectRequest();
            inValue.Body = new webServiceClient2.BorlandWS.GetUserObjectRequestBody();
            webServiceClient2.BorlandWS.GetUserObjectResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).GetUserObject(inValue);
            return retVal.Body.GetUserObjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.GetUserObjectResponse> webServiceClient2.BorlandWS.Service1Soap.GetUserObjectAsync(webServiceClient2.BorlandWS.GetUserObjectRequest request) {
            return base.Channel.GetUserObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.GetUserObjectResponse> GetUserObjectAsync() {
            webServiceClient2.BorlandWS.GetUserObjectRequest inValue = new webServiceClient2.BorlandWS.GetUserObjectRequest();
            inValue.Body = new webServiceClient2.BorlandWS.GetUserObjectRequestBody();
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).GetUserObjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.SetUserObjectResponse webServiceClient2.BorlandWS.Service1Soap.SetUserObject(webServiceClient2.BorlandWS.SetUserObjectRequest request) {
            return base.Channel.SetUserObject(request);
        }
        
        public bool SetUserObject(webServiceClient2.BorlandWS.User usr) {
            webServiceClient2.BorlandWS.SetUserObjectRequest inValue = new webServiceClient2.BorlandWS.SetUserObjectRequest();
            inValue.Body = new webServiceClient2.BorlandWS.SetUserObjectRequestBody();
            inValue.Body.usr = usr;
            webServiceClient2.BorlandWS.SetUserObjectResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).SetUserObject(inValue);
            return retVal.Body.SetUserObjectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.SetUserObjectResponse> webServiceClient2.BorlandWS.Service1Soap.SetUserObjectAsync(webServiceClient2.BorlandWS.SetUserObjectRequest request) {
            return base.Channel.SetUserObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.SetUserObjectResponse> SetUserObjectAsync(webServiceClient2.BorlandWS.User usr) {
            webServiceClient2.BorlandWS.SetUserObjectRequest inValue = new webServiceClient2.BorlandWS.SetUserObjectRequest();
            inValue.Body = new webServiceClient2.BorlandWS.SetUserObjectRequestBody();
            inValue.Body.usr = usr;
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).SetUserObjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.BorlandWS.IncreaseUserAgeResponse webServiceClient2.BorlandWS.Service1Soap.IncreaseUserAge(webServiceClient2.BorlandWS.IncreaseUserAgeRequest request) {
            return base.Channel.IncreaseUserAge(request);
        }
        
        public webServiceClient2.BorlandWS.User IncreaseUserAge(webServiceClient2.BorlandWS.User usr, int nIncrease) {
            webServiceClient2.BorlandWS.IncreaseUserAgeRequest inValue = new webServiceClient2.BorlandWS.IncreaseUserAgeRequest();
            inValue.Body = new webServiceClient2.BorlandWS.IncreaseUserAgeRequestBody();
            inValue.Body.usr = usr;
            inValue.Body.nIncrease = nIncrease;
            webServiceClient2.BorlandWS.IncreaseUserAgeResponse retVal = ((webServiceClient2.BorlandWS.Service1Soap)(this)).IncreaseUserAge(inValue);
            return retVal.Body.IncreaseUserAgeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.BorlandWS.IncreaseUserAgeResponse> webServiceClient2.BorlandWS.Service1Soap.IncreaseUserAgeAsync(webServiceClient2.BorlandWS.IncreaseUserAgeRequest request) {
            return base.Channel.IncreaseUserAgeAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.BorlandWS.IncreaseUserAgeResponse> IncreaseUserAgeAsync(webServiceClient2.BorlandWS.User usr, int nIncrease) {
            webServiceClient2.BorlandWS.IncreaseUserAgeRequest inValue = new webServiceClient2.BorlandWS.IncreaseUserAgeRequest();
            inValue.Body = new webServiceClient2.BorlandWS.IncreaseUserAgeRequestBody();
            inValue.Body.usr = usr;
            inValue.Body.nIncrease = nIncrease;
            return ((webServiceClient2.BorlandWS.Service1Soap)(this)).IncreaseUserAgeAsync(inValue);
        }
    }
}
