//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webServiceClient2.PaperlessService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.online.webapp.paperless.cl", ConfigurationName="PaperlessService.OnlinePortType")]
    public interface OnlinePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationDteCT", ReplyAction="urn:OnlineGenerationDteCTResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineGenerationDteCTResponse OnlineGenerationDteCT(webServiceClient2.PaperlessService.OnlineGenerationDteCTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationDteCT", ReplyAction="urn:OnlineGenerationDteCTResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationDteCTResponse> OnlineGenerationDteCTAsync(webServiceClient2.PaperlessService.OnlineGenerationDteCTRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationBol", ReplyAction="urn:OnlineGenerationBolResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineGenerationBolResponse OnlineGenerationBol(webServiceClient2.PaperlessService.OnlineGenerationBolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationBol", ReplyAction="urn:OnlineGenerationBolResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationBolResponse> OnlineGenerationBolAsync(webServiceClient2.PaperlessService.OnlineGenerationBolRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:BusinessReply", ReplyAction="urn:BusinessReplyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.BusinessReplyResponse BusinessReply(webServiceClient2.PaperlessService.BusinessReplyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BusinessReply", ReplyAction="urn:BusinessReplyResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.BusinessReplyResponse> BusinessReplyAsync(webServiceClient2.PaperlessService.BusinessReplyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultCT", ReplyAction="urn:ConsultCTResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.ConsultCTResponse ConsultCT(webServiceClient2.PaperlessService.ConsultCTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultCT", ReplyAction="urn:ConsultCTResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.ConsultCTResponse> ConsultCTAsync(webServiceClient2.PaperlessService.ConsultCTRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationCT", ReplyAction="urn:OnlineGenerationCTResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineGenerationCTResponse OnlineGenerationCT(webServiceClient2.PaperlessService.OnlineGenerationCTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationCT", ReplyAction="urn:OnlineGenerationCTResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationCTResponse> OnlineGenerationCTAsync(webServiceClient2.PaperlessService.OnlineGenerationCTRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRecCT", ReplyAction="urn:OnlineRecoveryRecCTResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineRecoveryRecCTResponse OnlineRecoveryRecCT(webServiceClient2.PaperlessService.OnlineRecoveryRecCTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRecCT", ReplyAction="urn:OnlineRecoveryRecCTResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryRecCTResponse> OnlineRecoveryRecCTAsync(webServiceClient2.PaperlessService.OnlineRecoveryRecCTRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationDte", ReplyAction="urn:OnlineGenerationDteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineGenerationDteResponse OnlineGenerationDte(webServiceClient2.PaperlessService.OnlineGenerationDteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationDte", ReplyAction="urn:OnlineGenerationDteResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationDteResponse> OnlineGenerationDteAsync(webServiceClient2.PaperlessService.OnlineGenerationDteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryCT", ReplyAction="urn:OnlineRecoveryCTResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineRecoveryCTResponse OnlineRecoveryCT(webServiceClient2.PaperlessService.OnlineRecoveryCTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryCT", ReplyAction="urn:OnlineRecoveryCTResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryCTResponse> OnlineRecoveryCTAsync(webServiceClient2.PaperlessService.OnlineRecoveryCTRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecovery", ReplyAction="urn:OnlineRecoveryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineRecoveryResponse OnlineRecovery(webServiceClient2.PaperlessService.OnlineRecoveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecovery", ReplyAction="urn:OnlineRecoveryResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryResponse> OnlineRecoveryAsync(webServiceClient2.PaperlessService.OnlineRecoveryRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRec", ReplyAction="urn:OnlineRecoveryRecResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineRecoveryRecResponse OnlineRecoveryRec(webServiceClient2.PaperlessService.OnlineRecoveryRecRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRec", ReplyAction="urn:OnlineRecoveryRecResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryRecResponse> OnlineRecoveryRecAsync(webServiceClient2.PaperlessService.OnlineRecoveryRecRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationBolCT", ReplyAction="urn:OnlineGenerationBolCTResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineGenerationBolCTResponse OnlineGenerationBolCT(webServiceClient2.PaperlessService.OnlineGenerationBolCTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGenerationBolCT", ReplyAction="urn:OnlineGenerationBolCTResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationBolCTResponse> OnlineGenerationBolCTAsync(webServiceClient2.PaperlessService.OnlineGenerationBolCTRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRecList", ReplyAction="urn:OnlineRecoveryRecListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineRecoveryRecListResponse OnlineRecoveryRecList(webServiceClient2.PaperlessService.OnlineRecoveryRecListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineRecoveryRecList", ReplyAction="urn:OnlineRecoveryRecListResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryRecListResponse> OnlineRecoveryRecListAsync(webServiceClient2.PaperlessService.OnlineRecoveryRecListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGeneration", ReplyAction="urn:OnlineGenerationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.OnlineGenerationResponse OnlineGeneration(webServiceClient2.PaperlessService.OnlineGenerationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:OnlineGeneration", ReplyAction="urn:OnlineGenerationResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationResponse> OnlineGenerationAsync(webServiceClient2.PaperlessService.OnlineGenerationRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:Consult", ReplyAction="urn:ConsultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webServiceClient2.PaperlessService.ConsultResponse Consult(webServiceClient2.PaperlessService.ConsultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Consult", ReplyAction="urn:ConsultResponse")]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.ConsultResponse> ConsultAsync(webServiceClient2.PaperlessService.ConsultRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.online.webapp.paperless.cl/xsd")]
    public partial class OnlineResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string causaField;
        
        private string codigoField;
        
        private string descripcionField;
        
        private string numero_folioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string causa {
            get {
                return this.causaField;
            }
            set {
                this.causaField = value;
                this.RaisePropertyChanged("causa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string numero_folio {
            get {
                return this.numero_folioField;
            }
            set {
                this.numero_folioField = value;
                this.RaisePropertyChanged("numero_folio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationDteCT", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationDteCTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public int args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public int args5;
        
        public OnlineGenerationDteCTRequest() {
        }
        
        public OnlineGenerationDteCTRequest(int args0, string args1, string args2, string args3, int args4, int args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationDteCTResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationDteCTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public webServiceClient2.PaperlessService.OnlineResponse @return;
        
        public OnlineGenerationDteCTResponse() {
        }
        
        public OnlineGenerationDteCTResponse(webServiceClient2.PaperlessService.OnlineResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationBol", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationBolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public int args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public int args5;
        
        public OnlineGenerationBolRequest() {
        }
        
        public OnlineGenerationBolRequest(int args0, string args1, string args2, string args3, int args4, int args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationBolResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationBolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineGenerationBolResponse() {
        }
        
        public OnlineGenerationBolResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusinessReply", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class BusinessReplyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        public int args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public int args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public long args5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=6)]
        public int args6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args7;
        
        public BusinessReplyRequest() {
        }
        
        public BusinessReplyRequest(int args0, string args1, string args2, int args3, int args4, long args5, int args6, string args7) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
            this.args6 = args6;
            this.args7 = args7;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BusinessReplyResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class BusinessReplyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public BusinessReplyResponse() {
        }
        
        public BusinessReplyResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultCT", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class ConsultCTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        public ConsultCTRequest() {
        }
        
        public ConsultCTRequest(int args0, string args1, string args2, string args3) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultCTResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class ConsultCTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public webServiceClient2.PaperlessService.OnlineResponse @return;
        
        public ConsultCTResponse() {
        }
        
        public ConsultCTResponse(webServiceClient2.PaperlessService.OnlineResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationCT", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationCTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public int args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public int args5;
        
        public OnlineGenerationCTRequest() {
        }
        
        public OnlineGenerationCTRequest(int args0, string args1, string args2, string args3, int args4, int args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationCTResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationCTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public webServiceClient2.PaperlessService.OnlineResponse @return;
        
        public OnlineGenerationCTResponse() {
        }
        
        public OnlineGenerationCTResponse(webServiceClient2.PaperlessService.OnlineResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecCT", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecCTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        public int args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public int args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public long args5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=6)]
        public int args6;
        
        public OnlineRecoveryRecCTRequest() {
        }
        
        public OnlineRecoveryRecCTRequest(int args0, string args1, string args2, int args3, int args4, long args5, int args6) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
            this.args6 = args6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecCTResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecCTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public webServiceClient2.PaperlessService.OnlineResponse @return;
        
        public OnlineRecoveryRecCTResponse() {
        }
        
        public OnlineRecoveryRecCTResponse(webServiceClient2.PaperlessService.OnlineResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationDte", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationDteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public int args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public int args5;
        
        public OnlineGenerationDteRequest() {
        }
        
        public OnlineGenerationDteRequest(int args0, string args1, string args2, string args3, int args4, int args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationDteResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationDteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineGenerationDteResponse() {
        }
        
        public OnlineGenerationDteResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryCT", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryCTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        public int args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public long args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public int args5;
        
        public OnlineRecoveryCTRequest() {
        }
        
        public OnlineRecoveryCTRequest(int args0, string args1, string args2, int args3, long args4, int args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryCTResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryCTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public webServiceClient2.PaperlessService.OnlineResponse @return;
        
        public OnlineRecoveryCTResponse() {
        }
        
        public OnlineRecoveryCTResponse(webServiceClient2.PaperlessService.OnlineResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecovery", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        public int args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public long args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public int args5;
        
        public OnlineRecoveryRequest() {
        }
        
        public OnlineRecoveryRequest(int args0, string args1, string args2, int args3, long args4, int args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryResponse() {
        }
        
        public OnlineRecoveryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRec", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        public int args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public int args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public long args5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=6)]
        public int args6;
        
        public OnlineRecoveryRecRequest() {
        }
        
        public OnlineRecoveryRecRequest(int args0, string args1, string args2, int args3, int args4, long args5, int args6) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
            this.args6 = args6;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryRecResponse() {
        }
        
        public OnlineRecoveryRecResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationBolCT", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationBolCTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public int args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public int args5;
        
        public OnlineGenerationBolCTRequest() {
        }
        
        public OnlineGenerationBolCTRequest(int args0, string args1, string args2, string args3, int args4, int args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationBolCTResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationBolCTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public webServiceClient2.PaperlessService.OnlineResponse @return;
        
        public OnlineGenerationBolCTResponse() {
        }
        
        public OnlineGenerationBolCTResponse(webServiceClient2.PaperlessService.OnlineResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecList", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        public OnlineRecoveryRecListRequest() {
        }
        
        public OnlineRecoveryRecListRequest(int args0, string args1, string args2, string args3) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineRecoveryRecListResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineRecoveryRecListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineRecoveryRecListResponse() {
        }
        
        public OnlineRecoveryRecListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGeneration", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=4)]
        public int args4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=5)]
        public int args5;
        
        public OnlineGenerationRequest() {
        }
        
        public OnlineGenerationRequest(int args0, string args1, string args2, string args3, int args4, int args5) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
            this.args4 = args4;
            this.args5 = args5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnlineGenerationResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class OnlineGenerationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public OnlineGenerationResponse() {
        }
        
        public OnlineGenerationResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Consult", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class ConsultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        public int args0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string args3;
        
        public ConsultRequest() {
        }
        
        public ConsultRequest(int args0, string args1, string args2, string args3) {
            this.args0 = args0;
            this.args1 = args1;
            this.args2 = args2;
            this.args3 = args3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultResponse", WrapperNamespace="http://webservices.online.webapp.paperless.cl", IsWrapped=true)]
    public partial class ConsultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.online.webapp.paperless.cl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public ConsultResponse() {
        }
        
        public ConsultResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnlinePortTypeChannel : webServiceClient2.PaperlessService.OnlinePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnlinePortTypeClient : System.ServiceModel.ClientBase<webServiceClient2.PaperlessService.OnlinePortType>, webServiceClient2.PaperlessService.OnlinePortType {
        
        public OnlinePortTypeClient() {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnlinePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineGenerationDteCTResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationDteCT(webServiceClient2.PaperlessService.OnlineGenerationDteCTRequest request) {
            return base.Channel.OnlineGenerationDteCT(request);
        }
        
        public webServiceClient2.PaperlessService.OnlineResponse OnlineGenerationDteCT(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationDteCTRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationDteCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            webServiceClient2.PaperlessService.OnlineGenerationDteCTResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationDteCT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationDteCTResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationDteCTAsync(webServiceClient2.PaperlessService.OnlineGenerationDteCTRequest request) {
            return base.Channel.OnlineGenerationDteCTAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationDteCTResponse> OnlineGenerationDteCTAsync(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationDteCTRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationDteCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationDteCTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineGenerationBolResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationBol(webServiceClient2.PaperlessService.OnlineGenerationBolRequest request) {
            return base.Channel.OnlineGenerationBol(request);
        }
        
        public string OnlineGenerationBol(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationBolRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationBolRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            webServiceClient2.PaperlessService.OnlineGenerationBolResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationBol(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationBolResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationBolAsync(webServiceClient2.PaperlessService.OnlineGenerationBolRequest request) {
            return base.Channel.OnlineGenerationBolAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationBolResponse> OnlineGenerationBolAsync(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationBolRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationBolRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationBolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.BusinessReplyResponse webServiceClient2.PaperlessService.OnlinePortType.BusinessReply(webServiceClient2.PaperlessService.BusinessReplyRequest request) {
            return base.Channel.BusinessReply(request);
        }
        
        public string BusinessReply(int args0, string args1, string args2, int args3, int args4, long args5, int args6, string args7) {
            webServiceClient2.PaperlessService.BusinessReplyRequest inValue = new webServiceClient2.PaperlessService.BusinessReplyRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            inValue.args6 = args6;
            inValue.args7 = args7;
            webServiceClient2.PaperlessService.BusinessReplyResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).BusinessReply(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.BusinessReplyResponse> webServiceClient2.PaperlessService.OnlinePortType.BusinessReplyAsync(webServiceClient2.PaperlessService.BusinessReplyRequest request) {
            return base.Channel.BusinessReplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.BusinessReplyResponse> BusinessReplyAsync(int args0, string args1, string args2, int args3, int args4, long args5, int args6, string args7) {
            webServiceClient2.PaperlessService.BusinessReplyRequest inValue = new webServiceClient2.PaperlessService.BusinessReplyRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            inValue.args6 = args6;
            inValue.args7 = args7;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).BusinessReplyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.ConsultCTResponse webServiceClient2.PaperlessService.OnlinePortType.ConsultCT(webServiceClient2.PaperlessService.ConsultCTRequest request) {
            return base.Channel.ConsultCT(request);
        }
        
        public webServiceClient2.PaperlessService.OnlineResponse ConsultCT(int args0, string args1, string args2, string args3) {
            webServiceClient2.PaperlessService.ConsultCTRequest inValue = new webServiceClient2.PaperlessService.ConsultCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            webServiceClient2.PaperlessService.ConsultCTResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).ConsultCT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.ConsultCTResponse> webServiceClient2.PaperlessService.OnlinePortType.ConsultCTAsync(webServiceClient2.PaperlessService.ConsultCTRequest request) {
            return base.Channel.ConsultCTAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.ConsultCTResponse> ConsultCTAsync(int args0, string args1, string args2, string args3) {
            webServiceClient2.PaperlessService.ConsultCTRequest inValue = new webServiceClient2.PaperlessService.ConsultCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).ConsultCTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineGenerationCTResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationCT(webServiceClient2.PaperlessService.OnlineGenerationCTRequest request) {
            return base.Channel.OnlineGenerationCT(request);
        }
        
        public webServiceClient2.PaperlessService.OnlineResponse OnlineGenerationCT(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationCTRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            webServiceClient2.PaperlessService.OnlineGenerationCTResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationCT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationCTResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationCTAsync(webServiceClient2.PaperlessService.OnlineGenerationCTRequest request) {
            return base.Channel.OnlineGenerationCTAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationCTResponse> OnlineGenerationCTAsync(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationCTRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationCTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineRecoveryRecCTResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineRecoveryRecCT(webServiceClient2.PaperlessService.OnlineRecoveryRecCTRequest request) {
            return base.Channel.OnlineRecoveryRecCT(request);
        }
        
        public webServiceClient2.PaperlessService.OnlineResponse OnlineRecoveryRecCT(int args0, string args1, string args2, int args3, int args4, long args5, int args6) {
            webServiceClient2.PaperlessService.OnlineRecoveryRecCTRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryRecCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            inValue.args6 = args6;
            webServiceClient2.PaperlessService.OnlineRecoveryRecCTResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecoveryRecCT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryRecCTResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineRecoveryRecCTAsync(webServiceClient2.PaperlessService.OnlineRecoveryRecCTRequest request) {
            return base.Channel.OnlineRecoveryRecCTAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryRecCTResponse> OnlineRecoveryRecCTAsync(int args0, string args1, string args2, int args3, int args4, long args5, int args6) {
            webServiceClient2.PaperlessService.OnlineRecoveryRecCTRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryRecCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            inValue.args6 = args6;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecoveryRecCTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineGenerationDteResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationDte(webServiceClient2.PaperlessService.OnlineGenerationDteRequest request) {
            return base.Channel.OnlineGenerationDte(request);
        }
        
        public string OnlineGenerationDte(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationDteRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationDteRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            webServiceClient2.PaperlessService.OnlineGenerationDteResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationDte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationDteResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationDteAsync(webServiceClient2.PaperlessService.OnlineGenerationDteRequest request) {
            return base.Channel.OnlineGenerationDteAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationDteResponse> OnlineGenerationDteAsync(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationDteRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationDteRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationDteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineRecoveryCTResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineRecoveryCT(webServiceClient2.PaperlessService.OnlineRecoveryCTRequest request) {
            return base.Channel.OnlineRecoveryCT(request);
        }
        
        public webServiceClient2.PaperlessService.OnlineResponse OnlineRecoveryCT(int args0, string args1, string args2, int args3, long args4, int args5) {
            webServiceClient2.PaperlessService.OnlineRecoveryCTRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            webServiceClient2.PaperlessService.OnlineRecoveryCTResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecoveryCT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryCTResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineRecoveryCTAsync(webServiceClient2.PaperlessService.OnlineRecoveryCTRequest request) {
            return base.Channel.OnlineRecoveryCTAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryCTResponse> OnlineRecoveryCTAsync(int args0, string args1, string args2, int args3, long args4, int args5) {
            webServiceClient2.PaperlessService.OnlineRecoveryCTRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecoveryCTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineRecoveryResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineRecovery(webServiceClient2.PaperlessService.OnlineRecoveryRequest request) {
            return base.Channel.OnlineRecovery(request);
        }
        
        public string OnlineRecovery(int args0, string args1, string args2, int args3, long args4, int args5) {
            webServiceClient2.PaperlessService.OnlineRecoveryRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            webServiceClient2.PaperlessService.OnlineRecoveryResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecovery(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineRecoveryAsync(webServiceClient2.PaperlessService.OnlineRecoveryRequest request) {
            return base.Channel.OnlineRecoveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryResponse> OnlineRecoveryAsync(int args0, string args1, string args2, int args3, long args4, int args5) {
            webServiceClient2.PaperlessService.OnlineRecoveryRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecoveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineRecoveryRecResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineRecoveryRec(webServiceClient2.PaperlessService.OnlineRecoveryRecRequest request) {
            return base.Channel.OnlineRecoveryRec(request);
        }
        
        public string OnlineRecoveryRec(int args0, string args1, string args2, int args3, int args4, long args5, int args6) {
            webServiceClient2.PaperlessService.OnlineRecoveryRecRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryRecRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            inValue.args6 = args6;
            webServiceClient2.PaperlessService.OnlineRecoveryRecResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecoveryRec(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryRecResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineRecoveryRecAsync(webServiceClient2.PaperlessService.OnlineRecoveryRecRequest request) {
            return base.Channel.OnlineRecoveryRecAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryRecResponse> OnlineRecoveryRecAsync(int args0, string args1, string args2, int args3, int args4, long args5, int args6) {
            webServiceClient2.PaperlessService.OnlineRecoveryRecRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryRecRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            inValue.args6 = args6;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecoveryRecAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineGenerationBolCTResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationBolCT(webServiceClient2.PaperlessService.OnlineGenerationBolCTRequest request) {
            return base.Channel.OnlineGenerationBolCT(request);
        }
        
        public webServiceClient2.PaperlessService.OnlineResponse OnlineGenerationBolCT(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationBolCTRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationBolCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            webServiceClient2.PaperlessService.OnlineGenerationBolCTResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationBolCT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationBolCTResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationBolCTAsync(webServiceClient2.PaperlessService.OnlineGenerationBolCTRequest request) {
            return base.Channel.OnlineGenerationBolCTAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationBolCTResponse> OnlineGenerationBolCTAsync(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationBolCTRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationBolCTRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationBolCTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineRecoveryRecListResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineRecoveryRecList(webServiceClient2.PaperlessService.OnlineRecoveryRecListRequest request) {
            return base.Channel.OnlineRecoveryRecList(request);
        }
        
        public string OnlineRecoveryRecList(int args0, string args1, string args2, string args3) {
            webServiceClient2.PaperlessService.OnlineRecoveryRecListRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryRecListRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            webServiceClient2.PaperlessService.OnlineRecoveryRecListResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecoveryRecList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryRecListResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineRecoveryRecListAsync(webServiceClient2.PaperlessService.OnlineRecoveryRecListRequest request) {
            return base.Channel.OnlineRecoveryRecListAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineRecoveryRecListResponse> OnlineRecoveryRecListAsync(int args0, string args1, string args2, string args3) {
            webServiceClient2.PaperlessService.OnlineRecoveryRecListRequest inValue = new webServiceClient2.PaperlessService.OnlineRecoveryRecListRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineRecoveryRecListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.OnlineGenerationResponse webServiceClient2.PaperlessService.OnlinePortType.OnlineGeneration(webServiceClient2.PaperlessService.OnlineGenerationRequest request) {
            return base.Channel.OnlineGeneration(request);
        }
        
        public string OnlineGeneration(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            webServiceClient2.PaperlessService.OnlineGenerationResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGeneration(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationResponse> webServiceClient2.PaperlessService.OnlinePortType.OnlineGenerationAsync(webServiceClient2.PaperlessService.OnlineGenerationRequest request) {
            return base.Channel.OnlineGenerationAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.OnlineGenerationResponse> OnlineGenerationAsync(int args0, string args1, string args2, string args3, int args4, int args5) {
            webServiceClient2.PaperlessService.OnlineGenerationRequest inValue = new webServiceClient2.PaperlessService.OnlineGenerationRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            inValue.args4 = args4;
            inValue.args5 = args5;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).OnlineGenerationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webServiceClient2.PaperlessService.ConsultResponse webServiceClient2.PaperlessService.OnlinePortType.Consult(webServiceClient2.PaperlessService.ConsultRequest request) {
            return base.Channel.Consult(request);
        }
        
        public string Consult(int args0, string args1, string args2, string args3) {
            webServiceClient2.PaperlessService.ConsultRequest inValue = new webServiceClient2.PaperlessService.ConsultRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            webServiceClient2.PaperlessService.ConsultResponse retVal = ((webServiceClient2.PaperlessService.OnlinePortType)(this)).Consult(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webServiceClient2.PaperlessService.ConsultResponse> webServiceClient2.PaperlessService.OnlinePortType.ConsultAsync(webServiceClient2.PaperlessService.ConsultRequest request) {
            return base.Channel.ConsultAsync(request);
        }
        
        public System.Threading.Tasks.Task<webServiceClient2.PaperlessService.ConsultResponse> ConsultAsync(int args0, string args1, string args2, string args3) {
            webServiceClient2.PaperlessService.ConsultRequest inValue = new webServiceClient2.PaperlessService.ConsultRequest();
            inValue.args0 = args0;
            inValue.args1 = args1;
            inValue.args2 = args2;
            inValue.args3 = args3;
            return ((webServiceClient2.PaperlessService.OnlinePortType)(this)).ConsultAsync(inValue);
        }
    }
}
